package com.example.hearandthere_test.util

object MusicState {
    const val ACTION_MUSIC_PLAY = "ACTION_MUSIC_PLAY"
    const val ACTION_MUSIC_PAUSE = "ACTION_MUSIC_PAUSE"
    const val ACTION_MUSIC_NEXT = "ACTION_MUSIC_NEXT"
    const val ACTION_MUSIC_LAST = "ACTION_MUSIC_LAST"
    const val ACTION_MUSIC_STOP = "ACTION_MUSIC_STOP"
    const val ACTION_MUSIC_SEEK_TO = "ACTION_MUSIC_SEEK_TO"

    const val ACTION_LOCATION_BASE_PLAY_STOP = "ACTION_LOCATION_BASE_PLAY_STOP"
    const val ACTION_TRACK_BASE_PLAY = "ACTION_TRACK_BASE_PLAY"


    const val ACTION_STATUS_MUSIC_PLAY = "ACTION_STATUS_MUSIC_PLAY"
    const val ACTION_STATUS_MUSIC_PAUSE = "ACTION_STATUS_MUSIC_PAUSE"
    const val ACTION_STATUS_MUSIC_COMPLETE = "ACTION_STATUS_MUSIC_COMPLETE"
    const val ACTION_STATUS_MUSIC_DURATION = "ACTION_STATUS_MUSIC_DURATION"

    const val ACTIVITY_REFRESH = "ACTIVITY_REFRESH"

    const val PARAM_MUSIC_DURATION = "PARAM_MUSIC_DURATION"
    const val PARAM_MUSIC_SEEK_TO = "PARAM_MUSIC_SEEK_TO"
    const val PARAM_MUSIC_CURRENT_POSITION = "PARAM_MUSIC_CURRENT_POSITION"

    const val PARAM_MUSIC_LIST_BY_TRACK = "PARAM_MUSIC_LIST_BY_TRACK"

    const val BS_ENTRY = "BS_ENTRY"
    const val MUSIC_NOW_PLAYING = "MUSIC_NOW_PLAYING"
    const val BS_REOPEN = "BS_REOPEN"
    const val MUSIC_INFO = "MUSIC_INFO"

    const val MUSIC_INFO_TRACK_TITLE = "MUSIC_INFO_TRACK_TITLE"
    const val MUSIC_INFO_AUDIO_TITLE = "MUSIC_INFO_AUDIO_TITLE"

    const val MUSIC_VP_CHANGE = "MUSIC_VP_CHANGE"
    const val MUSIC_VP_CHANGE_IDX = "MUSIC_VP_CHANGE_IDX"

    const val PLAYLIST_UP = "PLAYLIST_UP"

    const val NOWPLAY_MUSIC_IDX = "NOWPLAY_MUSIC_IDX"
    const val NOWPLAY_MUSIC_IDX_VALUE = "NOWPLAY_MUSIC_IDX_VALUE"
}